### ISSUE TITLE
Script para actualizar dependencias ya no funciona

### ISSUE THREAD

**Issue by oxcar** [ProjectPODER/abreportales#3]
Con el nuevo cambio de la [Plataforma Nacional de Transparencia](plataformadetransparencia.org.mx/), ha cambiado la URL y el formato en el que se pueden obtener las entidades.

La URL `https://esbmx.inai.org.mx/infomex3/sistemas_infomex` ya no funciona.

Es necesario actualizar el script `update_dependencias.js`.

**Comment by nez** [comment]
Hola @oxcar @martinszy, me parece que los cambios a la PNT rompen también app.js ya que cuando hago `node app.js` veo este error:

```
abreportales2/app.js:181
  cookieArray = cookieHeader.split("; Path=/")
                             ^

TypeError: Cannot read property 'split' of null
    at headersToCookieString (abreportales/app.js:181:30)
    at abreportales/app.js:126:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)```

**Comment by nez** [comment]
No se si es la causa pero veo que están usando cloudflare como protección vs ddos.

**Comment by martinszy** [comment]
Si cambiaron el sistema de cookies hay que re-hacer el login. Es un trabajito, si alguien tiene ganas de revisarlo, adelante.

**Comment by nez** [comment]
Además de lo que dices @martinszy, la url https://esbmx.inai.org.mx/infomex3/sistemas_infomex ya no sirve

**Comment by martinszy** [comment]
Lamento que los cambios en el sitio hayan roto toda la app. Hay que dedicarle un rato a investigar cómo funciona ahora. Voy a cambiar el readme para avisar que no anda.
